### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by Lukacma** [LangProc/langproc-2019-cw#15]
I would like to also ask to what extent are we supposed to implement arrays? Do we need to support array initialization or multidimensional/nested arrays?

**Comment by Lukacma** [comment]
Also should can we assume that size of the array will be given as a constant?

**Comment by johnwickerson** [comment]
As I have already described [here](https://github.com/LangProc/langproc-2019-cw/blob/master/c_compiler.md), variable-length arrays will not be tested. The other features could be tested; I suggest looking at the examples I gave you to get an idea of the kind of code I will try on your compiler.

**Comment by Lukacma** [comment]
Just for the completion's sake. Multidimensional arrays may be tested, however, we can assume that elements of the array will be declared by a constant not constant expression.
