### ISSUE TITLE
C-Translator: Input Restrictions

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-cw#2]
For the C to Python translator, can we assume that the C input code will always have a typed identified scope? 

This will always occur:
```
Format:

TYPE ID (PARAMS) {
     CONTENT
}



Such as:

int main(){
     int x = 0;
     return x;
}



Or simply:

void f(){}

```

This will never occur (by itself as a test):
```

Format:

{
     CONTENT
}



Such as:

{
     int x = 0;
}
```

**Comment by tobhil98** [comment]
It could be tested if it is a legal input. You should for example be able to translate:
```
int main(){
     int x = 0;
     {
         x = x + 5
     }
     return x;
}
```

A .c file which only contains a single scope with no return type and no function name is not syntactically valid and will therefore not be tested.
