### ISSUE TITLE
Constant expressions

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-cw#21]
This issue has been resolved somewhere else, but just to confirm: the following rules will have a _constant numerical value_ only (not even a constant expression like _3+4_ or something like _x-2_ with _x_ already defined) for _A_, _B_, etc...:

1. case(_A_)
2. global variable declarations: _type_ x = _A_
3. arrays declarations: _type_ arr[_A_][_B_]...

Could I get a confirmation on that?

**Comment by JaafarRammal** [comment]
I'll just evaluate and store whatever the expression on the stack and use the offset from the symbol table

**Comment by Lukacma** [comment]
Sorry for reopening, but I would like to get confirmation on that as well

**Comment by JaafarRammal** [comment]
It's calm, we will interpret the constant expressions while parsing before returning the node
