### ISSUE TITLE
&& || operators

### ISSUE THREAD

**Issue by BPulmannova** [LangProc/langproc-2019-cw#22]
I would like to ask about the &&  || / _and or_ operators in C to Python translation, as their return values differ, e.g.:

_2 && 3_ returns 1;
_2 and 3_ returns 3.

Do we need to take this into account?

**Comment by tobhil98** [comment]
Not really. As long as your logical operations produce non zero values to represent True then that should be fine. You could potentially use the python bool method if you want the values to be either 0 or 1
