### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-cw#23]
1. Will we be tested on C code with comments (// and /\*...*/)?
2. For personal debugging purposes, how do we create a multi-line comment in MIPS assembly? (I know for a fact a single line comment starts by a hashtag #)?

**Comment by tobhil98** [comment]
1. Probably not, but it could be useful for your own sake. Its only a simple regex match.
2. I don't think this is possible. Depending on the text editor you are using, there could be hotkeys for this if you are editing the assembly file.

**Comment by JaafarRammal** [comment]
Okay thanks.

I will close this, but if anyone finds out for assembly multi-line comments, drop a comment about it!
