### ISSUE TITLE
Operators Needed for Python Translator

### ISSUE THREAD

**Issue by JeetendraJoshi** [LangProc/langproc-2019-cw#24]
Test 17 requires the use of the not equal (!=) operator which is not explicitly mentioned in the specification. Do we need to implement this feature or is this technically an invalid test?

**Comment by tobhil98** [comment]
You should implement all C operators in Python

**Comment by JeetendraJoshi** [comment]
Does this mean we also need to implement operators such as "+=" and "-="? Is it possible to get an explicit list detailing which operators we can use?

**Comment by ymherklotz** [comment]
The spec for the Python Translator is quite strict, only the features present in [the spec](https://github.com/LangProc/langproc-2019-cw/blob/master/c_translator_templates.md) need to be supported. So `+=` and `-=` do not have to be supported.

**Comment by Lukacma** [comment]
Isn't this incompatible with the previous statement by @tobhil98?

**Comment by ymherklotz** [comment]
Yes, I guess so, if it is like last year though, not even `/` and `>` will be tested, because these are not in the spec.

At the top of the spec, it does say

> You are only required to support a subset of C when you translate to Python.

And the exact subset that has to be supported is described in that spec.

**Comment by JeetendraJoshi** [comment]
@ymherklotz so is test 17 technically invalid? as it contains a not equal to(not explicitly mentioned in spec)

**Comment by ymherklotz** [comment]
Yes you are right, I fixed the testcase, which should be equivalent but only contains `<`.

**Comment by tobhil98** [comment]
Yeah. I'm sorry for the confusion
