### ISSUE TITLE
Indication of global variables in functions

### ISSUE THREAD

**Issue by samuelgoh1525** [LangProc/langproc-2019-cw#26]
Hi, could I clarify whether this example given in the readme `c_translator_templates.md` is correct?

```python
x=0

def f():
    global x
    return x+10
```
Since the global variable x is only accessed and not modified in the function f(), shouldn't there be no need to declare `global x` inside the function?

Thank you!

**Comment by tobhil98** [comment]
Correct, the global x is not required to make the Python code work in this case. When you first enter the scope however, you won't necessarily know if you will be modifying the variable or not. You could therefore declare it as global in case you change it.

**Comment by samuelgoh1525** [comment]
In that case, will we be penalised for translating unnecessary code? Or even in a different example, where a function does not use any global variables at all, but we include all the global variables declared when we enter the scope.

For example, in one of the example c-to-python files provided:

> f8.c:
> ```c
> int x;
> 
> int f()
> {
>     x=x+1;
>     return x;
> }
> 
> int main()
> {
>     return f()+f();
> }
> ```
> f8.py:
> ```python
> x=0
> 
> def f():
>     global x
>     x=x+1
>     return x
> 
> def main():
>     return f()+f()
> 
> if __name__ == "__main__":
>     import sys
>     ret=main()
>     sys.exit(ret)
> ```

In f8.py, there is similarly no need to declare global x in the main function (as shown above), but would including that be wrong, since the translation would not be optimal? Or is it okay as long as the functionality of the code is preserved?

**Comment by tobhil98** [comment]
You will not be penalised for superfluous code. Your translator and compiler will only be marked on the correctness.

**Comment by samuelgoh1525** [comment]
Okay understood, thank you!
