### ISSUE TITLE
Warnings & Casting

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-cw#28]
I was wondering if we should compile valid code that generates warnings in GCC. For example:

```
int a[10] = {1,2, {1}};
int x = {1};
int a = 'a';
char c = "cat";
```

The first example with the array is sort of a pain, as it could extend to many nested brackets

Another annoying code:

```
int f(){int a = 3;return a;}
int main()
{
    int (*a)() = &f;
    return a() + &f;
}
```

**Comment by tobhil98** [comment]
I get compiler errors when trying to compile the first and fourth line with the C90 gcc flag.
I'm slightly unsure about the other two middle ones though. @ymherklotz might want to comment on this. 

Also, function pointers will not be tested.

**Comment by JaafarRammal** [comment]
I will take this as a confirmation 1st and 4th case, as well as function pointers, will not be tested.

No worries for the 2nd and 3rd one (their implementation is relatively easier). I will keep this open longer in case anyone has other comments

**Comment by ymherklotz** [comment]
They seem to compile fine for me with the following command:

```
gcc -Wall -Wextra -std=c89 -pedantic -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition main.c
```

I think all of those are completely valid C, and therefore could be tested. The [standard](http://port70.net/~nsz/c/c89/c89-draft.html#3.5.7) does say:

> The initializer for a scalar shall be a single expression, optionally enclosed in braces.

As a scalar is being initialised in the array, they could have braces around them.

Function pointers will not be tested though, so the last piece of code doesn't have to be handled.

**Comment by JaafarRammal** [comment]
Okay thanks. I guess I'll implement all four then. It's just that this one is very annoying when it grows to multidimensional arrays:

```
int a[10] = {1,2, {1}};
```

as it can become:

```
int a[5][4] = {{1,{2},3,{{4}}},{0},{0,3}};
```

which is a pain to keep track of scopes correctly

**Comment by ymherklotz** [comment]
Yeah definitely, I don't think I would make that a priority.

**Comment by ymherklotz** [comment]
@JaafarRammal Actually, I just looked at the spec again, and I think only 

```
int a[10] = {1,2, {1}};
int x = {1};
```

are valid. They would be quite horrible tests though so I really wouldn't spend too much time on that. It's better to support more features. 

The rest would come under type mismatches, which [the spec](https://github.com/LangProc/langproc-2019-cw/blob/master/c_compiler.md) says won't be tested.

**Comment by JaafarRammal** [comment]
Oh that sounds... okay. For type mismatch, does that mean we do not support things like:
```
int x = 3;
float a = x;
````
or:
```
float a = 3.3;
int x = a;
```

**Comment by ymherklotz** [comment]
Yeah that's how I interpret it at least, no implicit casting.

**Comment by JaafarRammal** [comment]
@ymherklotz sorry for the multiple questions, but can I assume therefore that for any assignment expression of the form ```left = right```, _left_ and _right_ (and of course their sub-components) will all be of the same type?

To be concrete, this is just for me to not verify the load / store operation of every single element on the right side (just get the type from the left side)

So for example, if I am given:

```
x = y + z - w
```

I can infer that _y_, _z_, and _w_ are of the same type of x?

**Comment by ymherklotz** [comment]
I thought that explicit casts were to be supported, but I can't seem to see them in the list of requirements.

So based on that I'd say you can make that assumption, but I'll check again and get back to you.

On 10 March 2020 12:31:33 GMT, Jaafar Rammal <notifications@github.com> wrote:
>@ymherklotz sorry for the multiple questions, but can I assume
>therefore that for any assignment expression of the form ```left =
>right```, _left_ and _right_ (and of course their sub-components) will
>all be of the same type?
>
>To be concrete, this is just for me to not verify the load / store
>operation of every single element on the right side (just get the type
>from the left side)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/LangProc/langproc-2019-cw/issues/28#issuecomment-597060817

-- 
Yann Herklotz
https://yannherklotz.com

**Comment by JaafarRammal** [comment]
@ymherklotz  any updates about explicit casts?

**Comment by ymherklotz** [comment]
Yeah, explicit casts won't be tested.

**Comment by JaafarRammal** [comment]
1- Sorry for being confused about this. No casting at all (implicit or explicit) will be required after all if I understood correctly

2- Is returning a char as an int considered as casting? So is the following a valid test:

```
int apple(char x){
  return x;
}
```

**Comment by ymherklotz** [comment]
Hmm I guess not, as the types are different.

**Comment by JaafarRammal** [comment]
@ymherklotz it appears that casting is required in the [following test](https://github.com/LangProc/langproc-2019-cw/blob/master/compiler_tests/float/pow.c):

```
float f(float x, int n)
{
    float acc=1.0f;
    int i=0;
    while(i<n){
        i++;
        acc=acc*x;
    }
    return acc;
}
```
