### ISSUE TITLE
Translator: function types

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-cw#3]
The [guidelines](https://github.com/LangProc/langproc-2019-cw/blob/master/c_translator_templates.md#required-constructs) for the translator implementation  states:

```
Definition of functions taking 0 or more integer parameters and with void or integer return type
```

Does integer return type refer to _int_ only or extends to other integer known types such as _unsigned_ and others?

**Comment by ymherklotz** [comment]
Integer return type here only refers to the int type, so you don’t have to worry about the others such as unsigned.
