### ISSUE TITLE
Query About ABI Compliance

### ISSUE THREAD

**Issue by aamanrebello** [LangProc/langproc-2019-cw#30]
Hi, I just wished to confirm that my (humble) understanding of the ABI compliance requirement is correct. To my understanding, our generated assembly needs to be the following because it complies with MIPS ABI:

1. It should not affect any persistent registers (e.g. s0, s1...). Either by not using them at all or by saving and restoring their values via stack. 

2. The stack may be used in any way that does not corrupt the stack frames created by the driver program. Although there may be a need to store function parameters (a0-a4) in the stack frame of the caller function (? not sure about this....)

Because of this, the driver program may operate with the confidence that our assembly will not "interfere" with it.

If you could let me know what is wrong/right in the above statements, I would be very grateful! I apologise if what I wrote is ambiguous:)

**Comment by ymherklotz** [comment]
1. Yep exactly, you can easily get around that by basically never using them.

2. Yes, **a0-a3** (4 registers) are for passing arguments, the rest should be passed through the stack (which as you said is allocated by the caller, so the function that is called needs to reach back in the stack to get those arguments). Maybe this [godbolt snippet](https://godbolt.org/z/hy2giJ) helps. You also have to make sure that everything is aligned properly in the registers a0-a3, for examples any int is basically cast to 32 bits (sign extended if necessary).

    Actually, looking at your question again, the parameters a0-a3 are never stored in the stack, the stack is only used if you have more than 4* arguments.

\* Assuming they are all 32 bits.

**Comment by aamanrebello** [comment]
Yes, this and the Godbolt Snippet is very helpful. Thanks!

What I noticed, though, is that the called function in the snippet [i.e. *int f(int, int..., int)*] stores the values of a0-a3 in the stack frame of the caller function [i.e. *int square()* ]. I'm guessing this is done in case function *f* will call some other function - hence you would want to preserve the old values of a0-a3.

And the caller function *square* basically allocates 4 words at the bottom of its frame to accommodate these values (a0-a3) pushed by *f*. So I guess, in all cases whenever a stack frame is allocated for a function, you will decrement the stack pointer by at least 16. To hold a0-a3.

If you could confirm that what I said above is correct, then I can close this issue.

**Comment by ymherklotz** [comment]
Yeah exactly, function f stores the values just in case it has to call other functions, optimisations will get rid of that.

And yes you always have to allocate at least 16 bytes for those registers so that they can be stored there. The [abi](http://math-atlas.sourceforge.net/devel/assembly/mipsabi32.pdf) says the following:

> However, at least four words (16 bytes) must always be reserved, even if the maximum number of arguments to any called function is fewer than four words

**Comment by aamanrebello** [comment]
Cool! Yeah that makes perfect sense, thank you!

**Comment by aamanrebello** [comment]
I apologise for bringing this up again, I just wished to further clarify - can we always expect that the stack frame of the main() function in the driver program will have those 16 vacant bytes available at the bottom? So that we can blindly store a0-a4 in that area from the function f() that we have to translate?

Or will there be some kind of optimisation at play that affects (read: reduces) these 16 vacant bytes when the main() is compiled with gcc?

**Comment by JaafarRammal** [comment]
According to [this](https://courses.cs.washington.edu/courses/cse410/09sp/examples/MIPSCallingConventionsSummary.pdf), the last four memory locations of any subroutine are reserved for whatever subroutine it calls

So yes, you can assume they are vacant

**Comment by aamanrebello** [comment]
Thanks a lot bro! That is a very useful source of information you have there!
