### ISSUE TITLE
Which MIPS instruction set can we use? And do we need to implement the ternary operator?

### ISSUE THREAD

**Issue by JeetendraJoshi** [LangProc/langproc-2019-cw#31]
I was just wondering which MIPS instruction set we are allowed to use.  Are we allowed to use the MIPS 1 set or the set of instructions that we constructed the simulator with in the first term?

**Comment by tobhil98** [comment]
As long as it runs on the qemu-mips simulator then it should be fine.

**Comment by JeetendraJoshi** [comment]
Also does the ternary operator need to be implemented as I am unsure as to whether this would be counted as a logical expression?

**Comment by tobhil98** [comment]
I would say that it would. It shouldn't be too hard if you have already implemented if-then-else statements
