### ISSUE TITLE
Pointers extent

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-cw#32]
To what extent do we have to implement pointers:
```
1- int ***a; return a[1][0][2];
2- ++*p;
3- *++p;
```

**Comment by tobhil98** [comment]
The project is fairly open-ended so you could implement those features if you want, but it is not something you should prioritise.

**Comment by JaafarRammal** [comment]
It's just that they fall over already implemented features such as multi-dimensional arrays and pre/post-increments, but with different syntax and context type (in terms of symbol table), which is fairly logical to implement but on the practical side we would have to rewrite many things to differentiate between, say, the multi-dimensional pointer and the multi-dimensional array

**Comment by tobhil98** [comment]
If they were tested, these features would probably not be in any more than a couple of test cases. You are better off focusing on the basic and intermediate features as they make up the majority of the test suite.
