### ISSUE TITLE
Sizeof pointer

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-cw#33]
1- I was wondering why the following code returns 8 and not 4:

```
int main()
{
    int b = 3;
    int * c = &b;
    return sizeof(c);
}
```

Why does a pointer take 8 bytes (2 words) instead of 4 bytes (1 word)?

2- My second questions is if we need to implement sizeof for expressions such as the following:

```
sizeof(a+b)
sizeof(4)
sizeof(2/3)
```

**Comment by tobhil98** [comment]
1. I think pointers are always 8 bytes if you are running on a 64bit machine. 
2. You would only need to get the size of a single variable or a type

**Comment by JaafarRammal** [comment]
So back on 1, since we are on 32 bits, can I confirm that we need 4 bytes only?

**Comment by tobhil98** [comment]
Yeah

**Comment by AdrianKoch3010** [comment]
In the spec it says that only sizeof variables and types will be tested i.e. something like
```c++
char (*a)[5];
int size = sizeof a;
// or 
size = sizeof(double[8]);
```
However, something like arr[2] or *p, where arr and p are variables of type array and pointer respectively is an expression and will, therefore, not be tested. I just wanted to make sure that something like this will not be tetsted:
```c++
int arr[5], *p;
int size = sizeof(arr[2]);
// or
size = sizeof(*p);
// or
size = sizeof(8 + 9);
```

**Comment by tobhil98** [comment]
Yeah, I think you will be right to assume that
