### ISSUE TITLE
Testing environment

### ISSUE THREAD

**Issue by AdrianKoch3010** [LangProc/langproc-2019-cw#34]
I was wondering if CMake will be installed on the test machines. This is important as the make files generated by it will check for CMake. Or will we be able to sudo apt install it in the make file?

My second question is if there is any requirement for the compiler executable in bin/c_compiler to be a compiled executable or could a be a bash file (with the file suffix being omitted)?

**Comment by akowal3** [comment]
you can modify `vagrantfile` provided in the lab to include all the necessary programs, which you are necessary for your compiler implementation, including cmake. Remember to include modified `vagrantfile` in the root of your GitHub directory. Also remember that only command which will be run is `make bin/c_compiler`, which means that you would need to call cmake from make.

**Comment by tobhil98** [comment]
If you do use cmake then you need to make sure you check in a version of the generated makefile. The compiler would still need to be built using the command: `make bin/c_compiler`.

For the second part of your question, as long as your bin/c_compiler program runs and produces the output as specified by the spec, then I cannot see why there would be an issue. Just make sure you read the "Program build and execution" section.

**Comment by JaafarRammal** [comment]
If we can fully execute the compiler with the vagrant file dependencies on the provided VM, does it ensure that it will execute fine on your testing environments?

**Comment by tobhil98** [comment]
The test script will launch your vagrant file and then run the two commands as specified in the "Program build and execution" sections.
You are recommended to clone your github repo into an empty folder to make sure that it works before your final submission.
