### ISSUE TITLE
GCC char pointers

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-cw#35]
I was wondering how does GCC expect char pointers to be in memory? Are the elements stored by words or by bytes?

Also, assume the following code:
```
void g(char *x){
     *x="hello";
}
```
Where is "hello" stored in memory? On the heap or on the called subroutine stack?

**Comment by ymherklotz** [comment]
From [3.1.4, [C89 Standard](http://port70.net/~nsz/c/c89/c89-draft.html#3.1.4)]

> A character string literal has static storage duration and type ``array of char ,'' and is initialized with the given characters.

This means storage is allocated for the string at compile time, this can be done using the following assembly.

```
$LC0:
        .ascii  "hello\000"
```

Where `$LCO` is a label that can be used to load it just like globals.

I don't think your code above compiles though, because the string literal returns a `const char *`, which you can't assign to a `char`. You have to compile the following instead.

```c
void g(const char *x){
     x="hello";
}
```

You can try that out yourself and see the resultant assembly.

**Comment by JaafarRammal** [comment]
Makes sense! Heap allocation seems to be the only solution indeed

**Comment by AdrianKoch3010** [comment]
The const keyword isn't tested though, right?

**Comment by tobhil98** [comment]
Correct

**Comment by JaafarRammal** [comment]
I think this issue was actually deviated from its purpose. I was wondering how are chars stored in memory when it comes to a normal array such as ```char a[7]``` or within a struct. Is it word by word or byte by byte?

Word by word:

```
  .----------.
  |    'a'   |
  .----------.
  |          | 
  .----------.
  |          | 
  .----------.
  |          | 
  .----------.
  |    'b'   | 
  .----------.
  |          |
  .----------.
```

Byte by byte:

```
  .----------.
  |    'a'   |
  .----------.
  |    'b'   | 
  .----------.
  |          | 
  .----------.
  |          | 
  .----------.
  |          | 
  .----------.
  |          |
  .----------.
```

If it is byte by byte, what is the policy when we have something like this:

```
struct a{
   int b;
   char c;
   char d;
   int e;
};
```

as in how does the spacing happens within the memory?

**Comment by ymherklotz** [comment]
[Figure 3-9:  Internal and Tail Padding](http://math-atlas.sourceforge.net/devel/assembly/mipsabi32.pdf) in the abi basically describes that.

> Aggregates (structures and arrays) and unions assume the alignment of their moststrictly aligned components.

Basically for arrays that will give byte by byte for `char`, and 2 byte by 2 byte for `short`.

For structs, that means that the alignment will be

```
    +-------------------------+
0x0 | int                     |
    +------+------+-----+-----+
0x4 | char | char |     |     |
    +------+------+-----+-----+
0x8 | int                     |
    +-------------------------+
```

**Comment by JaafarRammal** [comment]
Apologies for not reading the ABI more in depth, this clarifies everything, thanks for the explanation

Also for shorts, I thought we do not need to implement them?

**Comment by ymherklotz** [comment]
No worries, I just like to refer to the sources, these questions are good.

No shorts were just an example, don't need to be implemented.
