### ISSUE TITLE
Double and float 

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-cw#36]
1- After looking up doubles and floats, it appears that they have their own registers and own set of instructions. I was wondering if it is possible to use a floating point register to operate on integers

2- There a relatively complicated issue with doubles and ints when it comes to function parameters. This is highlighted in the following C / Assembly pairs (assembly only shows context of interest):

| Tables        | Are           | 
| ------------- |:-------------:|
| int square(double a, double b) {<br>return 0;<br>}      |swc1    $f12,8($fp)<br>swc1    $f13,12($fp)<br>swc1    $f14,16($fp)<br>swc1    $f15,20($fp) |
| int square(double a, int b) {<br>return 0;<br>}      |swc1    $f12,8($fp)<br>swc1    $f13,12($fp)<br>sw $6,16($fp) |
| int square(int a, double b) {<br>return 0;<br>}      |sw      $4,8($fp)<br>sw      $6,16($fp)<br>sw      $7,20($fp)|

As you can see, the first and second case make sense (doubles are in floating point registers, and integers are in classic registers). The third case is somehow strange, as the double was now stored in classic registers by the subroutine caller (in our case, GCC). Do we have to implement our compiler to such extent of parameters passing differentiation?

**Comment by ymherklotz** [comment]
1. I don't think so, you could if you transformed the integer into a floating point representation and then stored it in the floating point registers. Is there a situation in which you think you'll need that?

2. Yes, that is part of the mips ABI, so you will have to do the same if you want to interact properly with code that was generated by gcc, or if you want gcc to call your function correctly [3-17, [Mips ABI](http://math-atlas.sourceforge.net/devel/assembly/mipsabi32.pdf)]:

  > When the first argument is integral, the remaining arguments are passed in the integer registers.

**Comment by JaafarRammal** [comment]
For 1. it was just to avoid extensive type checking to see what register type I should use, and use by default the floating point registers

And thanks for 2.

**Comment by tobhil98** [comment]
It's also worth noting that floats have a smaller precision than ints, so the conversion might be problematic for larger numbers

**Comment by JaafarRammal** [comment]
Indeed that's a good point... it will be harder to make ints fit into those floating point registers that I'd rather just type check 😅

**Comment by JaafarRammal** [comment]
<s>1- The ABI is clear, thanks! I was just confused about a little part. As we know, for purely integer functions, even if we have only parameter input such as ```int f(int a)```, we are still allowed (and in some cases required) to store ```$a0-$a3``` on the stack of the caller. Is that the case for any type of parameter? Will there alway be at least four words free on the caller stack?

In other words, would including the following for any function cause a problem (```$sp``` points to the stack of the caller from the bottom where the arguments space is allocated)

```
sw $a0, 0($sp)
sw $a1, 4($sp)
sw $a2, 8($sp)
sw $a3, 12($sp)
```

Or are the first four words for the first arguments of the callee function that we can store within these four words?
</s>
@ymherklotz @tobhil98 @johnwickerson, very weird situation below here:

2- I was quite confused in [3-20] of the [MIPS ABI](http://math-atlas.sourceforge.net/devel/assembly/mipsabi32.pdf) for the third out of these examples:
```
d1, n1, n2 -> $f12, $6, $7
s1, n1, n2 -> $f12, $5, $6
d1, s1, s2 -> $f12, $f14, $6 // WHY?!
s1, s2, s3, s4 -> $f12, $f14, $6, $7
```

Why wasn't the double counted as 2 arguments? If you look further on [3-20], it contradicts the whole protocol
