### ISSUE TITLE
Memory and undefined locations

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-cw#37]
I wanted to confirm that we have freedom in defining whatever should go in an "undefined" memory location, or if we must initialize to 0. Assume the following code:

```
int a[30];
int main()
{
	int j=0;
	for(j;j<20;j++)
	{
		a[j]=j;
	}
	a[0]=10;
	return a[a[j]];
}
```

Initializing the array to 0 will return 10. Initializing the array randomly will return a segmentation fault OR any item in the array

**Comment by ymherklotz** [comment]
The standard says:

> If an object that has automatic storage duration is not initialized explicitly, its value is indeterminate.

So you don't have to initialise it to 0, the value could be anything.
