### ISSUE TITLE
Unsigned and int, pointer return functions

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-cw#38]
1- I was wondering what's the difference between unsigned and int. I noticed on [godbolt](https://godbolt.org) that for both, operations take the form of ```addu``` for example for both. Is that the case? What's the difference between both then?

2- Following on this, I wanted to confirm that only the types in the specifications and in the tests will be tested (I've asked many times, apologies). So nothing fancy like short, long, signed, etc...

3- The following [test](https://github.com/LangProc/langproc-2019-cw/blob/master/compiler_tests/strings/search.c) is a function that returns a pointer. I assume therefore these will be tested. Do we have to extend these to something like this:

```
int *f(int *a){
   return a;
}

int g(){
   int a = 3;
   int *b = &a;
   *f(b) = 4;
   return a;
}
```

Which in that case should return 4.

**Comment by ymherklotz** [comment]
1. Yeah there is no difference in addition between signed and unsigned, the main difference I can think of is comparison:

  - `(unsigned int)(-8) < (unsigned int)(7)` will be `false`.
  - `(int)(-8) < (int)(7)` will be `true`.

2. I don't think so.

3. Yes, I believe that is a valid test case.

**Comment by JaafarRammal** [comment]
The example clarifies it, thanks!
