### ISSUE TITLE
Multiple declarations

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-cw#39]
Do we have to implement the following for the <b>compiler</b>:

```
...
int a = 4, b, c = 1;
...
```

**Comment by tobhil98** [comment]
Yes, I would think so

**Comment by ymherklotz** [comment]
It's part of the features __not__ to be implemented [in the spec](https://github.com/LangProc/langproc-2019-cw/blob/master/c_compiler.md):

> the comma operator (for sequencing within expressions)

Most questions like "should this be implemented" can be answered directly from the spec, so check there first.

**Comment by tobhil98** [comment]
Ahh yes, sorry about that

**Comment by JaafarRammal** [comment]
My bad, I didn't realize a declaration was an expression as well

**Comment by ymherklotz** [comment]
Well these `a = 4, b, c = 1` are assignment _expressions_ right? It's true that declarations can't be sequenced.
