### ISSUE TITLE
Translator: Non-deterministic return

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-cw#4]
Assume the following valid C code:

```
int main(){
	int a;
	return a;
}
```

The corresponding python translation is:

```
def main():
	a=0
	return a

if __name__ == "__main__":
	import sys
	ret=main()
	sys.exit(ret)
```

The problem is the following: both are valid scripts, and it's a valid translation. But when using return-comparison based testing (as per the provided script), python returns 0, but C returns what looks to be a non-deterministic value (37 on my machine, 54 on my friend's machine). What is the policy concerning such tests?

**Comment by tobhil98** [comment]
As the output of the C program is undefined, the return value from the python code can be whatever you want it to be
