### ISSUE TITLE
Return at non-void type

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-cw#40]
Do we have to implement ```return;``` for non void types? If yes, I am not quite sure how they final _$v0_ value is decided

```
int main(){
   int a = 3;
   int b = a;
   return;
}
```

For example why the following code returns 8?

```
int main(){
	
	int x = 8;
	switch(x){
		case 8:
			x=87;
			return;
	}

       return x;
}
```

**Comment by tobhil98** [comment]
The return value is undefined, so it can be any value. Not sure why it's always returning 8 though. Could be because 8 was the last value to be placed in that return register

**Comment by JaafarRammal** [comment]
So I assume this will not be tested

**Comment by tobhil98** [comment]
Probably not... You need to make sure your compiler does not crash if this is the input though as it's valid c code

**Comment by JaafarRammal** [comment]
Ohh I understand. You could test something like:

```
int f(char *a){
    ...
    // some code to play with *a
    ...
    return;
}

int main(){
   char *c;
   int a = f(c); // or simply f(c)
   return c[2] == 'h';
}

**Comment by tobhil98** [comment]
Potentially, yeah

**Comment by JaafarRammal** [comment]
Does the ```return``` inside a switch act like a ```break``` or does it leave the whole function?

**Comment by johnwickerson** [comment]
`return` always leaves the whole function.
