### ISSUE TITLE
Struct and Enum definition scopes

### ISSUE THREAD

**Issue by AdrianKoch3010** [LangProc/langproc-2019-cw#42]
I was wondering if the definitions of struct and enum types respect the scope for nested definitions.

For example, is this valid C89?
```c++
struct Foo{
    int x;
    struct Bar {
      int y;  
    };
};

int main()
{
    struct Bar bar;
    bar.x = 9;
}
```

And regarding enums, are the enumerators bound to a scope or would the following be illegal?
```c++
enum E1 { a }:
enum E2 { a };
```

**Comment by ymherklotz** [comment]
I'm not quite sure what you mean for the first quesion, as that shouldn't compile, because `x` is not defined in `Bar`.

```c
enum E1 { a };

struct Foo{
    int x;
    struct Bar {
      int x;
    } random;
};

int main()
{
    struct Bar bar;
    bar.x = 9;
}
```

The above is completely valid though.

Enum values are global, so those declarations wouldn't be legal, they would have to have separate names.

**Comment by AdrianKoch3010** [comment]
Oh yeah sorry, I meant bar.y for the first question as you have rightly guessed :) Thanks!
