### ISSUE TITLE
Question regarding Program Constraints

### ISSUE THREAD

**Issue by aamanrebello** [LangProc/langproc-2019-cw#43]
This may come across as a rather silly question, but I still have no idea. It says in the spec that our programs should complete in 10 seconds and not use an "inordinate" amount of memory. The first criterion is very clear; the second not so much. So I was just wondering what exactly is meant by "inordinate" in this context? 

How would I know if I have crossed this "inordinate" limit? Would it happen if I generated highly unoptimised MIPS?

An second and last question I have is: is time taken by the compiler to build a factor that needs to be considered? Again, is there any upper limit on this?

I'm just trying to be sure of everything at this point:)

**Comment by ymherklotz** [comment]
Hmm I guess the main thing is as long as you don't have any memory leaks, memory won't be a problem. However, if your compiler uses 1GB just to compile a C file, that might be a bit too much. 

I don't think the time taken to build the compiler is really considered, and it should build fairly quickly anyways as long as you aren't using a lot of templates in C++. But again, if it takes 10 minutes to compile the compiler, that might be too much as well.

I would say as long as it seems reasonable to you, it should be fine.

**Comment by tobhil98** [comment]
Your Mips assembly does not need to be in anyway optimised either. The maximum file length is roughly 1MB, and anything longer than that the test script will just cut the end off, so you should be fine.

**Comment by aamanrebello** [comment]
Yes, this does make sense! Most of the MIPS files come to around 1 KB which is well within the limit. Thanks!
