### ISSUE TITLE
Structs assign

### ISSUE THREAD

**Issue by Fiwo735** [LangProc/langproc-2019-cw#46]
When exploring how structs assigning is performed both by Godbolt and GCC, I came across the fact that they both resort to using **memcpy** subroutine for structures that would require more than 8 registers to be loaded and stored. Is it valid for our code to use the **memcpy** subroutine? If not, should we copy a structure using one register at a time or simply use as many registers as it takes, assuming the structs that we are tested for won't be big enough to cause a problem?

`struct a a1;`
`struct a a2;`
`...`
`a1 = a2;`

**Comment by JaafarRammal** [comment]
Hmm I am not sure why you wouldn't be able to do it with only two registers. Can you not copy the elements of the first structure one by one while assigning them to the other structure?

Example:

```
struct a{
    int f;
    int g;
    ....
};

int main(){
   struct a a1;
   struct a a2;
   .... // some stuff 
   a1 = a2; // $L0
   return 0;
}
```

Assembly at ```$L0``` using only register ```$2``` (with ```$3``` for doubles):
```
...
lw      $2,8($fp)
sw      $2,16($fp)
lw      $2,12($fp)
sw      $2,20($fp)
...
```

Haven't really worked on structs so there might be issues I am not aware of, but that's a way you could deal with it

**Comment by Fiwo735** [comment]
Thanks for the detailed answer! I am  aware of this possibility, but my question is whether we could actually use the **memcpy** instead of this method, as this is what Godbolt and GCC do.

**Comment by JaafarRammal** [comment]
Oh I see. Yes indeed, it would be nice to use ```memcpy``` (makes life easier as you wouldn't check for the types and variables anymore, just the size of the struct)

**Comment by ymherklotz** [comment]
I can't seem to find code that will generate a memcpy, but as long as your assembly works with the mips-gcc assembler, and it follows the mips abi, it is fine.

**Comment by JaafarRammal** [comment]
A code that generates ```memcpy```

```
struct a{
    double a;
    double b;
    double c;
    double d;
    double e;
};

int main(){
    struct a a1;
    struct a a2;
    a1 = a2;
    return 0;
}
```

Basically any structure with more than 8 memory locations required

**Comment by tobhil98** [comment]
Yeah, as Yann said, as long as it runs on the qemu-mips simulator then it's fine.

**Comment by Fiwo735** [comment]
Ok, thanks!
