### ISSUE TITLE
Dealing with Structs

### ISSUE THREAD

**Issue by aamanrebello** [LangProc/langproc-2019-cw#47]
Hi, I was wondering if we will have to deal with struct pointers being passed as arguments from an external function in the driver program (I hope not:( )? 

If we do, I also wanted to know: how would an element of a struct be accessed in the called function? Like if you had: 

struct a{ int b, short c, short d};      defined in the driver program (compiled by gcc)

To deal with this struct as an argument, the called function (compiled by our compiler) would need some "knowledge" as to what elements the struct has, and in what order they are defined. Since our compiler (here) has no access to the struct definition (it is defined in the driver program compiled by gcc), my question is - how can this be dealt with?

I am merely curious - if dealing with this problem is too difficult, I guess I will just have to leave it!:)

**Comment by JaafarRammal** [comment]
If I understand your questions correctly, it's about how elements are ordered in the struct if an external function gives you a pointer to this struct.

I believe it will be the same ordering as with arrays



According to the spec, we only implement pointer types

**Comment by aamanrebello** [comment]
It is much more complicated than arrays tho, and arrays have nice number indexes.....anyway, I guess you are right, it is not mentioned in the spec, so it is unlikely to be tested I guess. @ymherklotz , @tobhil98 , would you be able to confirm?

**Comment by JaafarRammal** [comment]
The ordering is no different than arrays. Your symbol table will need to store a vector of indexing for the structure and store it as an array of elements (which have different types). Then every time you try to access an element from a struct pointer, you go to that location and offset by whatever your symbol table tells you about the element ordering in the structure. Similar to an array pointer, but the offset won't be a multiple of type size, but the sum of all the previous element types until reaching the element of interest

**Comment by aamanrebello** [comment]
Yes, you are right. I think what you mentioned is not too difficult to implement if the struct is declared in the .c file compiled by our compilers. Because then you just analyse the struct and make your entries in the symbol table. 

If the struct is declared in the driver file tho...... if you know how to do what you mentioned even in this case, then you are very intelligent. It is beyond me:) (and I hope it won't be tested :P )

**Comment by JaafarRammal** [comment]
The instance will be defined in the driver, but your function has a declaration of the structure itself (just like when you're calling externally defined functions, the function is defined in the driver, but you know what it looks like). 

I hope this helps, not sure if I'm right tho :D

**Comment by aamanrebello** [comment]
Aha, if you are right then that does sort out everything! Thanks a lot man!
