### ISSUE TITLE
Initializer Lists as bases for other tests

### ISSUE THREAD

**Issue by AdrianKoch3010** [LangProc/langproc-2019-cw#48]
Hey, I was wondering if we have to implement initializer lists for array and struct initialization. And if so, will they be used as the bases for your array test bench?
E.g.
```c++
int a[2] = { 3, 4 };
// The actual array testing
```

Lastly, in case we need initializer lists, will we be expected to support length inference ie.
```c++
int a[] = { 2, 3 }; 
```
Declares an array of size 2?

**Comment by JaafarRammal** [comment]
In addition to this, will we be tested on the following:

```
int a[3] = {[0...1] = 3};
```

**Comment by tobhil98** [comment]
You don't have to have the initialiser list working, but they will almost definitely be tested.
I am quite sure that you don't have to implement length inference, as the size of the array should always be given inside the square brackets. 
Also, @JaafarRammal, not too sure what you mean by this? I don't think this is valid c is it?

**Comment by ymherklotz** [comment]
I don't think that is valid C either, but in any case anything with ellipses (`...`) won't be tested.
