### ISSUE TITLE
String declaration 

### ISSUE THREAD

**Issue by raphaelbharel** [LangProc/langproc-2019-cw#51]
![449b010c-5117-4b68-8edd-5699b812c842](https://user-images.githubusercontent.com/53297838/77830625-c096d480-7164-11ea-823f-330a241a3a95.jpeg)

It appears that in GCC there can be multiple ways of declaring strings, depending on the initialisation. This appears to be an optimisation. Would we be penalised for sticking to the ".word" initialisation throughout?

**Comment by tobhil98** [comment]
No, the compiler is only marked on the correctness.

**Comment by raphaelbharel** [comment]
Thank you
