### ISSUE TITLE
Logical operations on floats/doubles vs type conversion

### ISSUE THREAD

**Issue by Fiwo735** [LangProc/langproc-2019-cw#52]
Following the previous issues raised here, I understand that our compilers won't be tested for any type conversion (implicit and explicit). However, I am not sure how to classify the following:

```
int i = 5;
float f1 = 1.5f;
float f2 = 2.5f;
f1 = f1 && f2; // float <- int
i= f1 && f2; // int <- int
```

The result of a logical operation is either zero or non-zero which would mean that a result of an operation involving two floats (or doubles) produces an int. In this case, is this line considered a type conversion:
`f1 = f1 && f2;`
and we are only going to be tested for this? :
`i= f1 && f2;`

**Comment by JaafarRammal** [comment]
To my knowledge any logical operation has a boolean output, therefore 1 or 0, therefore an INT. Assigning to a floating point would be casting, which we do not have to support. I would like to have a confirmation as well 😄

**Comment by ymherklotz** [comment]
Yes what @JaafarRammal said sounds right.

**Comment by Fiwo735** [comment]
Makes sense, thanks
