### ISSUE TITLE
External globals + exceptions

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-cw#53]
<s>1- Do we have to support the following:

```
extern int global;
```

And then define in another file:

```
int global = 42;
```
</s>

2- Do we have to support the following (global scope):

```
int y = 1;
int* pointer = &y;
```

3- Do we need to handle faulty yet valid code such as a division by zero, and break with the appropriate exit code?

**Comment by ymherklotz** [comment]
2. Yes I think that might be tested.

3. No, divide by 0 is undefined behaviour I think.
