### ISSUE TITLE
u and U suffix

### ISSUE THREAD

**Issue by Fiwo735** [LangProc/langproc-2019-cw#54]
As it was pointed here: [https://github.com/LangProc/langproc-2019-cw/issues/45](url), floating point constants will be always followed by 'f' or 'F'. Can the same be assumed for unsigned with 'u' and 'U'?

So this code would be tested:
```
unsigned u1 = 3u;
unsigned u2 = 4U;
```
But this one not:
```
unsigned u1 = 3;
```

**Comment by tobhil98** [comment]
You could have `unsigned  u1 = 3;` as you will be treating the 3 as an unsigned integer. This is not the same as casting where you actually have to convert the bits from one format to another.

**Comment by ymherklotz** [comment]
Same with `unsigned int u2 = -3;`.

**Comment by Fiwo735** [comment]
oh, makes sense, I get the difference between float casting and this, thanks!
