### ISSUE TITLE
Question About Simulating Target Environment

### ISSUE THREAD

**Issue by aamanrebello** [LangProc/langproc-2019-cw#55]
Hi, just a quick question - I was wondering which of the three ways can provide the best simulation of the target environment our compilers will be running in? I have a Windows machine. Ideally I would just go into college and run the compiler on one of the lab machines , but of course, that is not possible now:

1. Using Ubuntu Subsystem (version 18.04 LTS) on Windows (like you just download the app)

2. Using the vagrant file provided with the labs - however this sets up version 16.04 and the labs currently have version 18.04.

3. Updating the virtual machine created by the vagrant file to version 18.04.

4. A more recommended/better method?

I currently have options 1 and 2 working and tests seem to be working fine on these. Should I be happy with that?

**Comment by ymherklotz** [comment]
Well the project will be run with your vagrant file, so as long as it works with the vagrant file in your repository it will work during the tests.

So either 2. or 3., if you need any extra dependencies, you can add them to the vagrant file.

**Comment by aamanrebello** [comment]
Thank you, that makes things clear! So if I just use the vagrant file provided without updating anything on the vm, I guess that should be fine then?

**Comment by johnwickerson** [comment]
Yup that’s right. I’d just use the provided Vagrantfile if I were you.

**Comment by aamanrebello** [comment]
Cool! Thank you, sir!

**Comment by JaafarRammal** [comment]
I have an issue when trying to install and use VirtualBox on linux

```
jr4918@cloud-vm-**-***:VagrantEnv$ sudo dpkg -i ./virtualbox-5.1_5.1.10-112026~Ubuntu~xenial_amd64.deb
(Reading database ... 267848 files and directories currently installed.)
Preparing to unpack .../virtualbox-5.1_5.1.10-112026~Ubuntu~xenial_amd64.deb ...
Unpacking virtualbox-5.1 (5.1.10-112026~Ubuntu~xenial) over (5.1.10-112026~Ubuntu~xenial) ...
dpkg: dependency problems prevent configuration of virtualbox-5.1:
 virtualbox-5.1 depends on libcurl3 (>= 7.16.2); however:
  Package libcurl3 is not installed.
 virtualbox-5.1 depends on libpng12-0 (>= 1.2.13-4); however:
  Package libpng12-0 is not installed.
 virtualbox-5.1 depends on libqt5opengl5 (>= 5.0.2) | libqt5opengl5-gles (>= 5.0.2); however:
  Package libqt5opengl5 is not installed.
  Package libqt5opengl5-gles is not installed.
 virtualbox-5.1 depends on libqt5printsupport5 (>= 5.0.2); however:
  Package libqt5printsupport5 is not installed.
 virtualbox-5.1 depends on libvpx3 (>= 1.5.0); however:
  Package libvpx3 is not installed.

dpkg: error processing package virtualbox-5.1 (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (237-3ubuntu10.39) ...
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for shared-mime-info (1.9-2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 virtualbox-5.1
```

When I try to install ```libvpx3```:

```
jr4918@cloud-vm-**-***:VagrantEnv$ sudo apt-get install libvpx3.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libvpx3.
E: Couldn't find any package by glob 'libvpx3.'
E: Couldn't find any package by regex 'libvpx3.'
```

**Comment by tobhil98** [comment]
I've never seen that error before. Will your team mate be able to run it before the deadline?

**Comment by JaafarRammal** [comment]
@tobhil98 we've been trying to setup remotely on linux VM as well as on our Mac devices, without success. Since uni is closed, we do not have access to the machines. Any chance someone with a working Vagrant could test our package, please drop a tag ❤️ 

It's in Java, so won't be able really to benefit from code if that's an issue 😜

**Comment by tobhil98** [comment]
If you email it to me I can run it when I get home in about an hour

**Comment by JaafarRammal** [comment]
Thank you! Just to clarify, @johnwickerson, does the make file need to run the Vagrant Up?

We tried running with other people, same issue 😞

**Comment by tobhil98** [comment]
Your makefile does not need to run any vagrant commands. The test script will launch your vagrantfile if one is provided and run the make commands inside that. 
(My email is: fth2817@ic.ac.uk)

**Comment by ymherklotz** [comment]
Have you tried

```
sudo apt install virtualbox
```

`dpkg` does not install dependencies for you, and you may be installing the wrong version of virtualbox.

**Comment by JaafarRammal** [comment]
Yes it didn't work

Can we force ```wget``` on https in our vagrant?

**Comment by JaafarRammal** [comment]
@ymherklotz can I run these:

1- Can I access the /usr/local/lib
2- Can I "wget"
3- Can I create Export and alias

**Comment by JaafarRammal** [comment]
So just wrapping it up in case someone runs with the same issue in the future:
- Vagrant cannot navigate or curl as it's setting up the environment before creating any directories. The solution to this is pushing the dependencies in a folder with the submission and then ```sudo cp``` into ```/usr/local/lib``` in our case for Java
- Exporting path can be made within the main compiler script as it exports it for the running script session
- Unfortunately, there is no way of creating an alias as it is only specific for its own thread. We therefore had to push all the required builds of these aliases and link them within the project directory

Many thanks to @tobhil98 for tuning in and sparing time testing our package!
