### ISSUE TITLE
size of a pointer

### ISSUE THREAD

**Issue by xhsimonmo** [LangProc/langproc-2019-cw#56]
Hi, I just want to confirm that no testcase for "sizeof" would include size of a pointer, because I think the exact size of a pointer depends on the machine the program is running on, (for example, 8 bytes in 64 bits machine.)

So the return value of sizeof of a pointer would be undefined in the testing?

**Comment by JaafarRammal** [comment]
Resolved [here](https://github.com/LangProc/langproc-2019-cw/issues/33)

**Comment by xhsimonmo** [comment]
Thank you! Get it.
