### ISSUE TITLE
Open Source Libraries

### ISSUE THREAD

**Issue by Lukacma** [LangProc/langproc-2019-cw#7]
I was wondering if the use of open-source libraries ( in my case I was thinking about using LLVM library for creating IR) is permissible?

**Comment by johnwickerson** [comment]
It's fine to use tools like Lex and Yacc to help you build parts of your compiler, but I think relying on LLVM would be going against the spirit of this exercise. I mean, in the most extreme case, you could just implement your compiler by just calling `gcc` and printing out its result, and that's something I'd rather avoid -- it wouldn't teach you very much!

**Comment by JaafarRammal** [comment]
@johnwickerson @ymherklotz

Might sound like a weird question, but would implementing our compiler through calling `gcc` with `mips` target be penalized, or would such an implementation be awarded full marks over the tests it passes?

As of a side parentheses, I personally assume prohibiting `mips` target for `gcc` in the vagrant file and running our compiled code in a mips simulator would be enough to cancel this approach

**Comment by johnwickerson** [comment]
Well that would hardly be implementing your own compiler, would it!
