### ISSUE TITLE
Bison C++ Variants

### ISSUE THREAD

**Issue by Lukacma** [LangProc/langproc-2019-cw#9]
During my creation of parser, I realised that the union doesn't support objects. Fortunately, I found that bison now supports variants. However, variants were not used in the lab. Is there a specific reason you decided not to use them ? Will using variants cause me troubles in the future?

**Comment by akowal3** [comment]
Nothing is stopping you from using variants, however, passing objects between the bison and the c++ implementation is not ideal. A much better solution would be passing pointers to objects. 
Also, ensure that if you are using non-standard features ensure that you provide configured vagrantfile, which could be used to run your compiler.

**Comment by Lukacma** [comment]
I understand. I decided to use them so I can use smart pointers and vectors
